from collections.abc import Sequence
from typing import BinaryIO

class PdfPage: ...

class PdfReader:
    pages: Sequence[PdfPage]
    outline: Sequence[object] | None
    outlines: Sequence[object] | None
    page_labels: Sequence[str] | None

    def __init__(self, stream: str) -> None: ...
    def get_destination_page_number(self, dest: object) -> int: ...
    def get_outlines(self) -> Sequence[object]: ...

class PdfWriter:
    def __init__(self) -> None: ...
    def add_page(self, page: PdfPage) -> None: ...
    def write(self, stream: BinaryIO) -> None: ...
    def add_blank_page(self, width: float | None = ..., height: float | None = ...) -> None: ...
    def add_outline_item(self, title: str, page_number: int) -> object: ...
