from __future__ import annotations

from typing import Any

from .QtCore import QMargins, QObject, QPointF, Signal
from .QtPdf import QPdfDocument
from .QtWidgets import QWidget

class QPdfPageNavigator(QObject):
    currentPageChanged: Signal
    currentZoomChanged: Signal
    def __getattr__(self, name: str) -> Any: ...
    def jump(self, page: int, location: QPointF) -> None: ...

class QPdfView(QWidget):
    class ZoomMode:
        Custom: int
        FitToWidth: int
        FitInView: int

    class PageMode:
        MultiPage: int

    zoomFactorChanged: Signal
    zoomModeChanged: Signal

    def __init__(self, parent: QWidget | None = ...) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def setDocument(self, document: QPdfDocument) -> None: ...
    def pageNavigator(self) -> QPdfPageNavigator: ...
    def setZoomMode(self, mode: int | QPdfView.ZoomMode) -> None: ...
    def setZoomFactor(self, factor: float) -> None: ...
    def zoomFactor(self) -> float: ...
    def setDocumentMargins(self, margins: QMargins) -> None: ...
    def viewport(self) -> QWidget: ...
