from __future__ import annotations

from typing import Any, overload

from .QtCore import QItemSelectionModel, QObject, Qt, Signal
from .QtGui import QFont, QPixmap

class QWidget(QObject):
    def __init__(self, parent: QWidget | None = ...) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def font(self) -> QFont: ...
    def style(self) -> Any: ...
    def sender(self) -> QObject | None: ...
    def setProperty(self, name: str, value: object) -> None: ...
    def setAttribute(self, attribute: int, on: bool = ...) -> None: ...
    def setVisible(self, visible: bool) -> None: ...
    def setEnabled(self, enabled: bool) -> None: ...
    def setWindowTitle(self, title: str) -> None: ...
    def show(self) -> None: ...
    def hide(self) -> None: ...
    def close(self) -> None: ...
    def grab(self) -> QPixmap: ...
    def showEvent(self, event: Any) -> None: ...
    def resizeEvent(self, event: Any) -> None: ...

class QApplication(QWidget):
    def __init__(self, argv: list[str]) -> None: ...
    @staticmethod
    def instance() -> QApplication | None: ...
    @staticmethod
    def activeWindow() -> QWidget | None: ...
    @staticmethod
    def processEvents() -> None: ...
    def exec(self) -> int: ...

class QMainWindow(QWidget): ...

class QLayout(QObject):
    def addWidget(self, widget: QWidget, stretch: int = ...) -> None: ...
    def addLayout(self, layout: QLayout, stretch: int = ...) -> None: ...
    def addStretch(self, stretch: int = ...) -> None: ...
    def setContentsMargins(self, left: int, top: int, right: int, bottom: int) -> None: ...
    def setSpacing(self, spacing: int) -> None: ...

class QVBoxLayout(QLayout):
    def __init__(self, parent: QWidget | None = ...) -> None: ...

class QHBoxLayout(QLayout):
    def __init__(self, parent: QWidget | None = ...) -> None: ...

class QAbstractItemView(QWidget):
    class SelectionMode:
        NoSelection: int
        SingleSelection: int

    class SelectionBehavior:
        SelectRows: int

    class EditTrigger:
        NoEditTriggers: int

class QHeaderView(QWidget):
    class ResizeMode:
        Stretch: int
        Fixed: int
        ResizeToContents: int

class QTableWidget(QWidget):
    def __init__(self, rows: int, columns: int, parent: QWidget | None = ...) -> None: ...
    def rowCount(self) -> int: ...
    def selectionModel(self) -> QItemSelectionModel: ...

class QLineEdit(QWidget):
    textChanged: Signal
    returnPressed: Signal
    def text(self) -> str: ...

class QSpinBox(QWidget):
    valueChanged: Signal
    def value(self) -> int: ...

class QPushButton(QWidget):
    clicked: Signal
    @overload
    def __init__(self, parent: QWidget | None = ...) -> None: ...
    @overload
    def __init__(self, text: str, parent: QWidget | None = ...) -> None: ...

class QToolButton(QPushButton):
    class ToolButtonPopupMode:
        InstantPopup: int

    def __init__(self, parent: QWidget | None = ...) -> None: ...

class QLabel(QWidget):
    @overload
    def __init__(self, parent: QWidget | None = ...) -> None: ...
    @overload
    def __init__(self, text: str, parent: QWidget | None = ...) -> None: ...

class QComboBox(QWidget):
    currentTextChanged: Signal
    def currentText(self) -> str: ...

class QListWidget(QWidget):
    def addItem(self, item: QListWidgetItem) -> None: ...

class QListWidgetItem:
    def __init__(self, text: str) -> None: ...
    def setFlags(self, flags: int) -> None: ...

class QTabWidget(QWidget): ...

class QSplitter(QWidget):
    def __init__(self, orientation: int, parent: QWidget | None = ...) -> None: ...

class QMenu(QWidget): ...

class QFileDialog:
    @staticmethod
    def getSaveFileName(
        parent: QWidget | None,
        caption: str,
        dir: str = ...,
        filter: str = ...,
    ) -> tuple[str, str]: ...
    @staticmethod
    def getOpenFileName(
        parent: QWidget | None,
        caption: str,
        dir: str = ...,
        filter: str = ...,
    ) -> tuple[str, str]: ...

class QProgressDialog(QWidget):
    canceled: Signal
    def __init__(
        self,
        label_text: str,
        cancel_button_text: str,
        minimum: int,
        maximum: int,
        parent: QWidget | None = ...,
    ) -> None: ...

class QMessageBox(QWidget):
    class Icon:
        Critical: int
        Warning: int
        Information: int

    class StandardButton:
        Yes: int
        No: int

    @staticmethod
    def question(
        parent: QWidget | None,
        title: str,
        text: str,
        buttons: int,
        default_button: int,
    ) -> int: ...

Qt = Qt
