"""TOML rendering helpers for chapter files."""

from __future__ import annotations

from collections.abc import Iterable

from ...core.models import ChapterDefinition
from ...pdf.detection.report import ChapterDetectionReport
from .models import ChapterFileSessionMetadata


def render_chapters_toml(
    *,
    chapters: Iterable[ChapterDefinition],
    report: ChapterDetectionReport | None,
    session: ChapterFileSessionMetadata | None,
) -> str:
    """Render chapters and metadata into TOML text.

    Summary:
        Generate a TOML payload that can round-trip through load_chapter_file while still carrying
        optional detection diagnostics and session context.
    Inputs:
        - chapters: ChapterDefinition objects to serialize.
        - report: Optional detection report metadata to embed.
        - session: Optional session metadata to include in the output file.
    Outputs:
        - TOML string.
    Side effects:
        None.
    Error handling:
        None.
    Ties to other methods:
        Used by write_chapter_file.
    Why this exists:
        Keeping TOML rendering isolated makes the writer easier to read and test.
    """
    lines: list[str] = ["# Generated by chapter-splitter", ""]
    _append_session_section(lines=lines, session=session)
    _append_detection_section(lines=lines, report=report)
    _append_chapter_sections(lines=lines, chapters=chapters)
    return "\n".join(lines).rstrip() + "\n"


def _append_session_section(
    *,
    lines: list[str],
    session: ChapterFileSessionMetadata | None,
) -> None:
    """Append the optional [session] TOML section.

    Summary:
        Serialize session metadata fields when the caller provided them.
    Inputs:
        - lines: Mutable TOML line buffer.
        - session: Optional session metadata to serialize.
    Outputs:
        - None.
    Side effects:
        Appends lines to the provided buffer.
    Error handling:
        No-ops when session is None.
    Ties to other methods:
        Used by render_chapters_toml.
    Why this exists:
        Optional TOML sections are easier to reason about when rendered in dedicated helpers.
    """
    if session is None:
        return
    lines.append("[session]")
    if session.pdf_path is not None:
        lines.append(f'pdf_path = "{toml_escape(session.pdf_path)}"')
    if session.total_pages is not None:
        lines.append(f"total_pages = {int(session.total_pages)}")
    if session.saved_at is not None:
        lines.append(f'saved_at = "{toml_escape(session.saved_at)}"')
    if session.source is not None:
        lines.append(f'source = "{toml_escape(session.source)}"')
    lines.append("")


def _append_detection_section(
    *,
    lines: list[str],
    report: ChapterDetectionReport | None,
) -> None:
    """Append the optional [detection] TOML section.

    Summary:
        Serialize detection metadata for users who want provenance alongside exported chapters.
    Inputs:
        - lines: Mutable TOML line buffer.
        - report: Optional detection report to serialize.
    Outputs:
        - None.
    Side effects:
        Appends lines to the provided buffer.
    Error handling:
        No-ops when report is None.
    Ties to other methods:
        Used by render_chapters_toml.
    Why this exists:
        Detection metadata should remain optional and visually separated from chapter definitions.
    """
    if report is None:
        return
    lines.append("[detection]")
    lines.append(f'strategy = "{toml_escape(report.strategy)}"')
    lines.append(f"confidence = {float(report.confidence):.6f}")
    lines.append(f"outline_entries = {int(report.outline_entries)}")
    if report.toc_start_page is not None:
        lines.append(f"toc_start_page = {int(report.toc_start_page)}")
    lines.append(f"toc_pages_scanned = {int(report.toc_pages_scanned)}")
    lines.append(
        "warnings = [" + ", ".join(f'"{toml_escape(warning)}"' for warning in report.warnings) + "]"
    )
    lines.append("")


def _append_chapter_sections(
    *,
    lines: list[str],
    chapters: Iterable[ChapterDefinition],
) -> None:
    """Append one [[chapters]] section per chapter definition.

    Summary:
        Serialize the core chapter data in the stable file format used by CLI and GUI workflows.
    Inputs:
        - lines: Mutable TOML line buffer.
        - chapters: Chapter definitions to serialize.
    Outputs:
        - None.
    Side effects:
        Appends lines to the provided buffer.
    Error handling:
        None.
    Ties to other methods:
        Used by render_chapters_toml.
    Why this exists:
        Chapter serialization is the stable core of the file format and should be isolated.
    """
    for chapter in chapters:
        lines.append("[[chapters]]")
        lines.append(f'title = "{toml_escape(chapter.title)}"')
        lines.append(f"start_page = {int(chapter.start_page)}")
        lines.append(f"end_page = {int(chapter.end_page)}")
        lines.append("")


def toml_escape(value: str) -> str:
    """Escape a string for use in a TOML basic string.

    Summary:
        Keep chapter titles, session fields, and warning messages safe for TOML output.
    Inputs:
        - value: Raw string to escape.
    Outputs:
        - Escaped string safe for TOML basic string quoting.
    Side effects:
        None.
    Error handling:
        None.
    Ties to other methods:
        Used by render_chapters_toml and its helper functions.
    Why this exists:
        Escaping rules should remain centralized so writer behavior stays deterministic.
    """
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    escaped = escaped.replace("\r\n", "\n").replace("\r", "\n")
    escaped = escaped.replace("\n", "\\n").replace("\t", "\\t")
    return escaped


__all__ = ["render_chapters_toml", "toml_escape"]
