"""TOML rendering helpers for chapter files."""

from __future__ import annotations

from collections.abc import Iterable

from ...core.models import ChapterDefinition
from ...pdf.detection.report import ChapterDetectionReport
from .models import ChapterFileSessionMetadata


def render_chapters_toml(
    *,
    chapters: Iterable[ChapterDefinition],
    report: ChapterDetectionReport | None,
    session: ChapterFileSessionMetadata | None,
) -> str:
    """Render chapters and metadata into TOML text."""
    lines: list[str] = ["# Generated by chapter-splitter", ""]
    _append_session_section(lines=lines, session=session)
    _append_detection_section(lines=lines, report=report)
    _append_chapter_sections(lines=lines, chapters=chapters)
    return "\n".join(lines).rstrip() + "\n"


def _append_session_section(
    *,
    lines: list[str],
    session: ChapterFileSessionMetadata | None,
) -> None:
    """Append the optional [session] TOML section."""
    if session is None:
        return
    lines.append("[session]")
    if session.pdf_path is not None:
        lines.append(f'pdf_path = "{toml_escape(session.pdf_path)}"')
    if session.total_pages is not None:
        lines.append(f"total_pages = {int(session.total_pages)}")
    if session.saved_at is not None:
        lines.append(f'saved_at = "{toml_escape(session.saved_at)}"')
    if session.source is not None:
        lines.append(f'source = "{toml_escape(session.source)}"')
    lines.append("")


def _append_detection_section(
    *,
    lines: list[str],
    report: ChapterDetectionReport | None,
) -> None:
    """Append the optional [detection] TOML section."""
    if report is None:
        return
    lines.append("[detection]")
    lines.append(f'strategy = "{toml_escape(report.strategy)}"')
    lines.append(f"confidence = {float(report.confidence):.6f}")
    lines.append(f"outline_entries = {int(report.outline_entries)}")
    if report.toc_start_page is not None:
        lines.append(f"toc_start_page = {int(report.toc_start_page)}")
    lines.append(f"toc_pages_scanned = {int(report.toc_pages_scanned)}")
    lines.append(
        "warnings = [" + ", ".join(f'"{toml_escape(warning)}"' for warning in report.warnings) + "]"
    )
    lines.append("")


def _append_chapter_sections(
    *,
    lines: list[str],
    chapters: Iterable[ChapterDefinition],
) -> None:
    """Append one [[chapters]] section per chapter definition."""
    for chapter in chapters:
        lines.append("[[chapters]]")
        lines.append(f'title = "{toml_escape(chapter.title)}"')
        lines.append(f"start_page = {int(chapter.start_page)}")
        lines.append(f"end_page = {int(chapter.end_page)}")
        lines.append("")


def toml_escape(value: str) -> str:
    """Escape a string for use in a TOML basic string."""
    named_escapes = {
        "\b": "\\b",
        "\t": "\\t",
        "\n": "\\n",
        "\f": "\\f",
        "\r": "\\r",
        '"': '\\"',
        "\\": "\\\\",
    }
    escaped: list[str] = []
    for character in value:
        replacement = named_escapes.get(character)
        if replacement is not None:
            escaped.append(replacement)
        elif ord(character) < 0x20 or ord(character) == 0x7F:
            escaped.append(f"\\u{ord(character):04X}")
        else:
            escaped.append(character)
    return "".join(escaped)


__all__ = ["render_chapters_toml", "toml_escape"]
